/** @jsxImportSource react */

import 'app/config/tailwind/global.css'
import 'setimmediate'
import 'raf/polyfill'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { StylesProvider } from 'app/provider/styles-provider.web'
import { TrpcProvider } from '../contexts/TrpcContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TrpcProvider>
          <StylesProvider>{children}</StylesProvider>
        </TrpcProvider>
      </body>
    </html>
  )
}
